environment:
    type: "MemoryGym"
    name: "MysteryPath-Grid-v0"
    reset_params:
        start-seed: 0
        num-seeds: 100000
        agent_scale: 0.25
        cardinal_origin_choice: [0, 1, 2, 3]
        show_origin: False
        show_goal: False
        visual_feedback: True
        reward_goal: 1.0
        reward_fall_off: 0.0
        reward_path_progress: 0.0
gamma: 0.995
lamda: 0.95
updates: 10000
epochs: 3
n_workers: 32
worker_steps: 512
n_mini_batch: 8
value_loss_coefficient: 0.5
hidden_layer_size: 512
max_grad_norm: 0.25
recurrence: 
    sequence_length: -1
    hidden_state_size: 512
    layer_type: gru
    reset_hidden_state: True
learning_rate_schedule:
    initial: 2.75e-4
    final: 1.0e-5
    power: 1.0
    max_decay_steps: 10000
beta_schedule:
    initial: 0.001
    final: 0.000001
    power: 1.0
    max_decay_steps: 10000
clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 10000