environment:
    type: "PocMemoryEnv"
gamma: 0.99
lamda: 0.95
updates: 30
epochs: 4
n_workers: 16
worker_steps: 128
n_mini_batch: 8
value_loss_coefficient: 0.1
hidden_layer_size: 64
max_grad_norm: 0.5
recurrence: 
    sequence_length: 8
    hidden_state_size: 32
    layer_type: gru
    reset_hidden_state: True
learning_rate_schedule:
    initial: 3.0e-4
    final: 3.0e-4
    power: 1.0
    max_decay_steps: 30
beta_schedule:
    initial: 0.001
    final: 0.0001
    power: 1.0
    max_decay_steps: 30
clip_range_schedule:
    initial: 0.2
    final: 0.2
    power: 1.0
    max_decay_steps: 30